package com.why.test.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.why.test.bean.Cart;

import com.why.test.db.CartDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartDaoConfig;

    private final CartDao cartDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        cartDao = new CartDao(cartDaoConfig, this);

        registerDao(Cart.class, cartDao);
    }
    
    public void clear() {
        cartDaoConfig.clearIdentityScope();
    }

    public CartDao getCartDao() {
        return cartDao;
    }

}
